### ISSUE TITLE
Feature items order and position

### ISSUE THREAD

**Issue by CatherineIles** [kentcc/staffcareservices#8]
I've added a fourth feature item to the homepage (the one about the new site). I'd expect it to appear first because it's the newest (or be able to control the order on the homepage through the order on in the tree) but the item is currently appearing fourth and in an odd place on the page. See screen grab. Please could you fix? Thanks.
![untitled-1](https://cloud.githubusercontent.com/assets/10434416/9655452/f29ef8f0-5228-11e5-998a-bba8b8d1b4e1.jpg)

**Comment by CharlesCarnell** [comment]
This is the [Isotope.JS](http://isotope.metafizzy.co/) and the default sorting. The design lends itself to content of varying heights, can this be handled in content @CatherineIles?

**Comment by CharlesCarnell** [comment]
Ordering is now also resolved.
